services:
  # --- Your Go Application Service ---
  app:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 on your local machine to port 8080 in the container
    depends_on:
      - mongo  # Tells Docker to start the 'mongo' service before starting the 'app' service
      - redis  # Also wait for the 'redis' service
    networks:
      - app-network

  # --- MongoDB Service ---
  mongo:
    image: mongo:6.0 # Use a specific version of MongoDB
    ports:
      - "27017:27017" # Map the port so you can connect from your local machine if needed
    volumes:
      - mongo-data:/data/db # Persist MongoDB data on your local machine
    networks:
      - app-network

  # --- Redis Service ---
  redis:
    image: redis:6-alpine # Use the same version as your tests for consistency
    ports:
      - "6379:6379" # Map the port for local connections
    volumes:
      - redis-data:/data # Persist Redis data
    networks:
      - app-network

# Define the network for services to communicate
networks:
  app-network:
    driver: bridge

# Define the volumes for data persistence
volumes:
  mongo-data:
  redis-data: